"""Edited title spelling

Revision ID: 0f3d235e61cb
Revises: 
Create Date: 2025-11-16 15:02:29.556353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f3d235e61cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=False))
        batch_op.drop_column('titile')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('titile', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_column('title')

    # ### end Alembic commands ###
